# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_transaction_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
